variables:
- name: serviceConnection
  value: azure-service-connection-mg
- name: resource-group
  value: hub-spoke-$(Build.BuildId)
- name: location
  value: eastus
- name: template-location
  value: '/solutions/basic-web-app/*'
- name: template-name
  value: 'azuredeploy.json'  
- name: ttk-skip-test
  value: 'IDs-Should-Be-Derived-From-ResourceIDs'

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - '/solutions/basic-web-app/*'
    exclude:
      - '/solutions/basic-web-app/README.md'
      
pr:
  branches:
    include:
    - master
  paths:
    include:
      - '/solutions/basic-web-app/*'
    exclude:
      - '/solutions/basic-web-app/README.md'

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true
      
stages:

# Run ARM TTK and publish test results (Windows only)
- stage: armTemplateToolkit

  jobs:
  - job: armttk
    pool:
      vmImage: 'windows-latest'
    continueOnError: false
    timeoutInMinutes: 20

    steps:
           
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: '$(System.DefaultWorkingDirectory)\*-armttk.xml'
      condition: always()

