variables:
  - name: location
    value: southcentralus
  - name: template-location
    value: "/solutions/secure-hybrid-network/*"
  - name: template-name
    value: "azuredeploy.json"
  - name: adminUserName
    value: "azureadmin"
  - name: pester-script-location
    value: "/tests/Test.ARMTemplate.ps1"
  - name: ttk-skip-test
    value: "DependsOn-Best-Practices,IDs-Should-Be-Derived-From-ResourceIDs,Secure-Params-In-Nested-Deployments"
  - name: artifactsLocationTemplate
    value: "https://raw.githubusercontent.com/mspnp/samples/main/solutions/secure-hybrid-network/"
  - name: mock-on-prem-resource-group-name
    value: secure-moc-onprem-$(Build.BuildId)
  - name: azure-network-resource-group-name
    value: secure-vnet-azure-$(Build.BuildId)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "/solutions/secure-hybrid-network/*"
    exclude:
      - "/solutions/secure-hybrid-network/README.md"

pr:
  branches:
    include:
      - main
  paths:
    include:
      - "/solutions/secure-hybrid-network/*"
    exclude:
      - "/solutions/secure-hybrid-network/README.md"

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - main
    always: true

stages:
  # Run ARM TTK and publish test results (Windows only)
  # - stage: armTemplateToolkit

  #   jobs:
  #   - job: armttk
  #     pool:
  #       vmImage: 'windows-latest'
  #     continueOnError: false
  #     timeoutInMinutes: 20

  #     steps:

  #     - task: PowerShell@2
  #       displayName: ARM-TTK and Pester
  #       inputs:
  #         targetType: 'inline'
  #         script: |
  #           git clone https://github.com/Azure/arm-ttk.git --quiet $env:BUILD_ARTIFACTSTAGINGDIRECTORY\arm-ttk
  #           import-module $env:BUILD_ARTIFACTSTAGINGDIRECTORY\arm-ttk\arm-ttk
  #           Install-Module Pester -AllowClobber -RequiredVersion 4.10.1 -Force -SkipPublisherCheck -AcceptLicense
  #           Import-Module Pester -RequiredVersion 4.10.1 -ErrorAction Stop
  #           $results = Invoke-Pester -Script @{Path = "$(System.DefaultWorkingDirectory)$(pester-script-location)"; Parameters = @{TemplatePath = "$(System.DefaultWorkingDirectory)$(template-location)$(template-name)"; Skip = "$(ttk-skip-test)"}} -OutputFormat NUnitXml -OutputFile TEST-ARMTemplate.xml -PassThru
  #           if ($results.TestResult.Result -contains "Failed") {Write-Error -Message "Test Failed"}

  #     - task: PublishTestResults@2
  #       inputs:
  #         testResultsFormat: 'NUnit'
  #         testResultsFiles: TEST-ARMTemplate.xml
  #       condition: always()

  # Deploy template
  - stage: validateAndDeploy
    dependsOn: []

    jobs:
      - job: arm
        pool:
          vmImage: ubuntu-latest
        continueOnError: false
        timeoutInMinutes: 240

        steps:
          - task: AzureCLI@2
            displayName: Validate template (validation api)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                uriTemplate=$(artifactsLocationTemplate)
                deployUri="${uriTemplate/REPLACEREF/$(Build.SourceVersion)}azuredeploy.json"
                artifactUri="${uriTemplate/REPLACEREF/$(Build.SourceVersion)}"
                az deployment sub validate --template-uri $deployUri --location eastus --parameters resourceGrouplocation=$(location) mocOnPremResourceGroup=$(mock-on-prem-resource-group-name) azureNetworkResourceGroup=$(azure-network-resource-group-name) adminUserName=$(adminUserName) adminPassword=$(adminPassword) --name validate-$(Build.BuildId)

          - task: AzureCLI@2
            displayName: Deploy template
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                uriTemplate=$(artifactsLocationTemplate)
                deployUri="${uriTemplate/REPLACEREF/$(Build.SourceVersion)}azuredeploy.json"
                artifactUri="${uriTemplate/REPLACEREF/$(Build.SourceVersion)}"
                az deployment sub create --template-uri $deployUri --location eastus --parameters resourceGrouplocation=$(location) mocOnPremResourceGroup=$(mock-on-prem-resource-group-name) azureNetworkResourceGroup=$(azure-network-resource-group-name) adminUserName=$(adminUserName) adminPassword=$(adminPassword) --name deploy-$(Build.BuildId)

          - task: AzureCLI@2
            displayName: Deploy template again
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                uriTemplate=$(artifactsLocationTemplate)
                deployUri="${uriTemplate/REPLACEREF/$(Build.SourceVersion)}azuredeploy.json"
                artifactUri="${uriTemplate/REPLACEREF/$(Build.SourceVersion)}"
                az deployment sub create --template-uri $deployUri --location eastus --parameters resourceGrouplocation=$(location) mocOnPremResourceGroup=$(mock-on-prem-resource-group-name) azureNetworkResourceGroup=$(azure-network-resource-group-name) adminUserName=$(adminUserName) adminPassword=$(adminPassword) --name deploy-$(Build.BuildId)

  # Clean up deployment
  - stage: cleanupResourceGroupBasic
    dependsOn: validateAndDeploy
    condition: always()

    jobs:
      - job: deleteResourceGroup
        pool:
          vmImage: ubuntu-latest
        continueOnError: false
        timeoutInMinutes: 20

        steps:
          - task: AzureCLI@2
            displayName: Delete resource group
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az group delete --resource-group $(mock-on-prem-resource-group-name) --yes --no-wait
                az group delete --resource-group $(azure-network-resource-group-name) --yes --no-wait
