variables:
  - name: location
    value: southcentralus
  - name: adminUserName
    value: "azureadmin"
  - name: mock-on-prem-resource-group-name
    value: secure-mock-onprem-$(Build.BuildId)
  - name: azure-network-resource-group-name
    value: secure-vnet-azure-$(Build.BuildId)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "/solutions/secure-hybrid-network/*"
    exclude:
      - "/solutions/secure-hybrid-network/README.md"

pr:
  branches:
    include:
      - main
  paths:
    include:
      - "/solutions/secure-hybrid-network/*"
    exclude:
      - "/solutions/secure-hybrid-network/README.md"

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - main
    always: true

stages:
  # Deploy template
  - stage: validateAndDeploy
    dependsOn: []

    jobs:
      - job: deploy
        pool:
          vmImage: ubuntu-latest
        continueOnError: false
        timeoutInMinutes: 240

        steps:
          - task: AzureCLI@2
            displayName: Validate template (validation api)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              workingDirectory: $(System.DefaultWorkingDirectory)/solutions/secure-hybrid-network
              inlineScript: |
                az deployment sub validate --template-file azuredeploy.bicep --location eastus --parameters resourceGrouplocation=$(location) mockOnPremResourceGroup=$(mock-on-prem-resource-group-name) azureNetworkResourceGroup=$(azure-network-resource-group-name) adminUserName=$(adminUserName) adminPassword=$(adminPassword) sharedKey=$(sharedKey) --name validate-$(Build.BuildId)

          - task: AzureCLI@2
            displayName: Deploy template
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              workingDirectory: $(System.DefaultWorkingDirectory)/solutions/secure-hybrid-network
              inlineScript: |
                az deployment sub create --template-file azuredeploy.bicep --location eastus --parameters resourceGrouplocation=$(location) mockOnPremResourceGroup=$(mock-on-prem-resource-group-name) azureNetworkResourceGroup=$(azure-network-resource-group-name) adminUserName=$(adminUserName) adminPassword=$(adminPassword) sharedKey=$(sharedKey) --name deploy-$(Build.BuildId)

          - task: AzureCLI@2
            displayName: Deploy template again
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              workingDirectory: $(System.DefaultWorkingDirectory)/solutions/secure-hybrid-network
              inlineScript: |
                az deployment sub create --template-file azuredeploy.bicep --location eastus --parameters resourceGrouplocation=$(location) mockOnPremResourceGroup=$(mock-on-prem-resource-group-name) azureNetworkResourceGroup=$(azure-network-resource-group-name) adminUserName=$(adminUserName) adminPassword=$(adminPassword) sharedKey=$(sharedKey) --name deploy-$(Build.BuildId)

  # Clean up deployment
  - stage: cleanupResourceGroupBasic
    dependsOn: validateAndDeploy
    condition: always()

    jobs:
      - job: deleteResourceGroup
        pool:
          vmImage: ubuntu-latest
        continueOnError: false
        timeoutInMinutes: 20

        steps:
          - task: AzureCLI@2
            displayName: Delete resource group
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az group delete --resource-group $(mock-on-prem-resource-group-name) --yes --no-wait
                az group delete --resource-group $(azure-network-resource-group-name) --yes --no-wait
